### GET DE JUGADORES
GET http://localhost:1234/jugadores

### GET DE JUGADORES
GET http://localhost:1234/jugadores/sin-equipo

### GET DE JUGADORES
GET http://localhost:1234/jugadores/con-equipo

### GET de jugadores y su equipo
GET http://localhost:1234/jugadores/equipo/lospalos

### POST de Jugador
POST http://localhost:1234/jugadores
Content-Type:  application/json

{
    "jugador": "Alejandro E. Suarez",
    "nacimiento": "1997-03-11",
    "dni": 40281424,
    "email": "Elniggaster@gmail.com",
    "contacto": 3774556611,
    "posicionP": "lo que venga anga probre",
    "posicionS": "Polifuncional pero mal en todo",
    "puntaje": 5,
    "imagen":"https://i6j5a8n9.rocketcdn.me/wp-content/uploads/2020/03/Jugadores-NBA-Coronavirus-COVID-19-1.jpg",
    "equipoBoolean": true,
    "equipoActual": "Los negros",
    "equipo": "losnegros"
}

### Actualizar un Valor
PATCH http://localhost:1234/jugadores/2
Content-Type:  application/json

{
    "equipoBoolean": false,
    "equipoActual": null,
    "equipo": null
}