### GET DE JUGADORES
GET http://localhost:1234/jugadores

### GET DE JUGADORES
GET http://localhost:1234/jugadores/sin-equipo

### GET DE JUGADORES
GET http://localhost:1234/jugadores/con-equipo

### GET de jugadores y su equipo
GET http://localhost:1234/jugadores/equipo/lospalos

### POST de Jugador
POST http://localhost:1234/jugadores
Content-Type:  application/json

{
    "jugador": "Nancy 2",
    "nacimiento": "2003-09-18",
    "dni": 43514445,
    "email": "lauti@gmail.com",
    "contacto": 3774556611,
    "posicionP": "Base",
    "posicionS": "Polifuncional",
    "puntaje": 75,
    "imagen":"https://i6j5a8n9.rocketcdn.me/wp-content/uploads/2020/03/Jugadores-NBA-Coronavirus-COVID-19-1.jpg",
    "equipoBoolean": "Los Pichichen",
    "equipoActual": false,
    "equipo": null
}